%YAML:1.0

# Sensor extrinsics wrt. the body-frame. This is the transformation of the
# vicon body origin to the body frame.
global_position_topic: "/vicon/firefly_sbx/firefly_sbx"
body_T_p: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.33638, -0.01749,  0.94156,  0.06901,
          -0.02078, -0.99972, -0.01114, -0.02781,
           0.94150, -0.01582, -0.33665, -0.12395,
           0.0,      0.0,      0.0,      1.0] 
